apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilitysoft
  namespace: grp01eq1-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilitysoft
  template:
    metadata:
      labels:
        app: mobilitysoft
    spec:
      containers:
        - name: mobilitysoft
          image: DOCKER_USERNAME/mobilitysoft-eq01:IMAGE_TAG_MOBILITY
          ports:
            - containerPort: 9000 
          envFrom:
            - configMapRef:
                name: mobilitysoft-config
            - secretRef:
                name: db-credentials
          resources:
            requests:
              cpu: "75m"
              memory: "75Mi"
            limits:
              cpu: "150m"
              memory: "150Mi"
